.PHONY: install
install:
	@mkdir $(INSTALL_PATH)/include/libsiridb
	@cp ../include/*.h $(INSTALL_PATH)/include/libsiridb/
	@cp $(FN) $(INSTALL_PATH)/lib/$(FN)

.PHONY: uninstall
uninstall:
	@rm -f $(INSTALL_PATH)/include/libsiridb/*.h
	@rmdir $(INSTALL_PATH)/include/libsiridb/
	@rm -f $(INSTALL_PATH)/lib/$(FN)

