.PHONY: install
install:
	mkdir /usr/include/siridb
	cp ../include/*.h /usr/include/siridb/
	cp siridb-connector-c.so /usr/lib/x86_64-linux-gnu/siridb-connector-c.so

.PHONY: uninstall
uninstall:
	rm -f /usr/include/siridb/*.h
	rmdir /usr/include/siridb/
	rm -f /usr/lib/x86_64-linux-gnu/siridb-connector-c.so

